### ISSUE TITLE
Environment Documentation To-Do 

### ISSUE THREAD

**Issue by Frexmax** [Frexmax/BoardGameAI#1]
- [x] Create documentation for Tic-Tac-Toe environment
- [x] Create documentation for Connect4 environment
- [x]  Create documentation for Checkers environment
