### ISSUE TITLE
Algorithm Documentation To-Do

### ISSUE THREAD

**Issue by Frexmax** [Frexmax/BoardGameAI#2]
- [x] Create documentation for Monte-Carlo-Tree Search
- [x] Create documentation for Actor-Critic 
- [x] Create documentation for all trainer sub-systems
- [x] Create documentation for trainer
